USE [master]
GO
/****** Object:  Database [KPAssessment]    Script Date: 2023-10-31 20:50:15 ******/
CREATE DATABASE [KPAssessment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KPAssessment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\KPAssessment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KPAssessment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\KPAssessment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [KPAssessment] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KPAssessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KPAssessment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KPAssessment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KPAssessment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KPAssessment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KPAssessment] SET ARITHABORT OFF 
GO
ALTER DATABASE [KPAssessment] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [KPAssessment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KPAssessment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KPAssessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KPAssessment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KPAssessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KPAssessment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KPAssessment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KPAssessment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KPAssessment] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KPAssessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KPAssessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KPAssessment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KPAssessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KPAssessment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KPAssessment] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [KPAssessment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KPAssessment] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [KPAssessment] SET  MULTI_USER 
GO
ALTER DATABASE [KPAssessment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KPAssessment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KPAssessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KPAssessment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KPAssessment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KPAssessment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [KPAssessment] SET QUERY_STORE = ON
GO
ALTER DATABASE [KPAssessment] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [KPAssessment]
GO
/****** Object:  Schema [KPAssessment]    Script Date: 2023-10-31 20:50:15 ******/
CREATE SCHEMA [KPAssessment]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [KPAssessment].[GroupPermission]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [KPAssessment].[GroupPermission](
	[GroupsGroupId] [uniqueidentifier] NOT NULL,
	[PermissionsPermissionId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_GroupPermission] PRIMARY KEY CLUSTERED 
(
	[GroupsGroupId] ASC,
	[PermissionsPermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [KPAssessment].[Groups]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [KPAssessment].[Groups](
	[GroupId] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Groups] PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [KPAssessment].[GroupUser]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [KPAssessment].[GroupUser](
	[GroupsGroupId] [uniqueidentifier] NOT NULL,
	[UsersUserId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_GroupUser] PRIMARY KEY CLUSTERED 
(
	[GroupsGroupId] ASC,
	[UsersUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [KPAssessment].[Permissions]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [KPAssessment].[Permissions](
	[PermissionId] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Permissions] PRIMARY KEY CLUSTERED 
(
	[PermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [KPAssessment].[Users]    Script Date: 2023-10-31 20:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [KPAssessment].[Users](
	[UserId] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [KPAssessment].[GroupPermission]  WITH CHECK ADD  CONSTRAINT [FK_GroupPermission_Groups_GroupsGroupId] FOREIGN KEY([GroupsGroupId])
REFERENCES [KPAssessment].[Groups] ([GroupId])
ON DELETE CASCADE
GO
ALTER TABLE [KPAssessment].[GroupPermission] CHECK CONSTRAINT [FK_GroupPermission_Groups_GroupsGroupId]
GO
ALTER TABLE [KPAssessment].[GroupPermission]  WITH CHECK ADD  CONSTRAINT [FK_GroupPermission_Permissions_PermissionsPermissionId] FOREIGN KEY([PermissionsPermissionId])
REFERENCES [KPAssessment].[Permissions] ([PermissionId])
ON DELETE CASCADE
GO
ALTER TABLE [KPAssessment].[GroupPermission] CHECK CONSTRAINT [FK_GroupPermission_Permissions_PermissionsPermissionId]
GO
ALTER TABLE [KPAssessment].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GroupUser_Groups_GroupsGroupId] FOREIGN KEY([GroupsGroupId])
REFERENCES [KPAssessment].[Groups] ([GroupId])
ON DELETE CASCADE
GO
ALTER TABLE [KPAssessment].[GroupUser] CHECK CONSTRAINT [FK_GroupUser_Groups_GroupsGroupId]
GO
ALTER TABLE [KPAssessment].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GroupUser_Users_UsersUserId] FOREIGN KEY([UsersUserId])
REFERENCES [KPAssessment].[Users] ([UserId])
ON DELETE CASCADE
GO
ALTER TABLE [KPAssessment].[GroupUser] CHECK CONSTRAINT [FK_GroupUser_Users_UsersUserId]
GO
USE [master]
GO
ALTER DATABASE [KPAssessment] SET  READ_WRITE 
GO
